// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfc9LESCBPPcCCwSOJ8JMC_328fNjoGI',
    appId: '1:364692800921:web:e9daf5cd5f22eb342a3f08',
    messagingSenderId: '364692800921',
    projectId: 'flutter-crm-prove',
    authDomain: 'flutter-crm-prove.firebaseapp.com',
    storageBucket: 'flutter-crm-prove.appspot.com',
    measurementId: 'G-ZYMPFM6R5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8cJvFDpgW0CeKWpp3ZuQj4isAXdBk-mA',
    appId: '1:364692800921:android:3a16ded0c53b50e62a3f08',
    messagingSenderId: '364692800921',
    projectId: 'flutter-crm-prove',
    storageBucket: 'flutter-crm-prove.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_3nhgGgAm0cgEWI85oBWTen-XTfaODs',
    appId: '1:364692800921:ios:19f62422c443c6aa2a3f08',
    messagingSenderId: '364692800921',
    projectId: 'flutter-crm-prove',
    storageBucket: 'flutter-crm-prove.appspot.com',
    iosBundleId: 'es.aures.flutterCrmProve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_3nhgGgAm0cgEWI85oBWTen-XTfaODs',
    appId: '1:364692800921:ios:19f62422c443c6aa2a3f08',
    messagingSenderId: '364692800921',
    projectId: 'flutter-crm-prove',
    storageBucket: 'flutter-crm-prove.appspot.com',
    iosBundleId: 'es.aures.flutterCrmProve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUfc9LESCBPPcCCwSOJ8JMC_328fNjoGI',
    appId: '1:364692800921:web:60e906a09207891f2a3f08',
    messagingSenderId: '364692800921',
    projectId: 'flutter-crm-prove',
    authDomain: 'flutter-crm-prove.firebaseapp.com',
    storageBucket: 'flutter-crm-prove.appspot.com',
    measurementId: 'G-JXKL38YRKX',
  );
}
